apiVersion: apps/v1
kind: Deployment 
metadata:
  name: rest-api
  labels:
    app: rest-api
spec:
  selector:
    matchLabels:
      app: rest-api
  replicas: 1 # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: rest-api
    spec:
      volumes:
      - name: json-data
        hostPath:
          path: /data
      containers:
      - name: json-server
        image: clue/json-server
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: json-data
          mountPath: /data
        # Resource Limits
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "64Mi"
            cpu: "150m"
