apiVersion: v1
kind: Pod
metadata:
  name: rest-api
spec:
  volumes:
  - name: json-data
    hostPath:
      path: /data
  containers:
  - name: json-server
    image: clue/json-server
    volumeMounts:
    - name: json-data
      mountPath: /data
      #Resource Limits
    resources:
      requests:
        memory: "32Mi"
        cpu: "100m"
      limits:
        memory: "64Mi"
        cpu: "150m"

